---
name: Linters

"on":
  pull_request:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          filter_mode: nofilter

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          filter_mode: nofilter

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run shfmt
        uses: reviewdog/action-shfmt@v1
        with:
          filter_mode: nofilter

  bashly:
    name: bashly
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🏗️ Setup ruby and bashly
        uses: ruby/setup-ruby@v1
      - name: 🚀 Run bashly
        run: bashly generate --upgrade
      - name: Checks if there are any uncommitted changes
        run: |
          clean=$(git status | grep "nothing to commit")
          if [ -z "$clean" ]; then
              echo "There are uncommitted changes"
               git --no-pager diff
              exit 1
          else
              echo "Branch is clean"
          fi
